'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFile } = require('child_process');
const { HOME_DIR, ensureDirs } = require('./config');
const { relaunchArgv } = require('./runtime');

const TASK_NAME = 'AI News Wallpaper';
const LEGACY_TASKS = ['AI News Wallpaper Logon'];
const LAUNCHER_PATH = path.join(HOME_DIR, 'run-hidden.vbs');
const TASK_XML_PATH = path.join(HOME_DIR, 'task.xml');

function run(exe, args) {
  return new Promise((resolve) => {
    execFile(exe, args, { windowsHide: true, timeout: 30000 }, (err, stdout, stderr) => {
      resolve({
        ok: !err,
        code: err ? (typeof err.code === 'number' ? err.code : 1) : 0,
        stdout: (stdout || '').toString(),
        stderr: (stderr || '').toString() || (err ? err.message : '')
      });
    });
  });
}

/** Full path, because PATH lookups for system tools are unreliable under some shells. */
function schtasksExe() {
  const root = process.env.SystemRoot || 'C:\\Windows';
  const full = path.join(root, 'System32', 'schtasks.exe');
  return fs.existsSync(full) ? full : 'schtasks.exe';
}

/**
 * Never put a quote character inside a schtasks argument: Node refuses to spawn
 * on Windows when an argument cannot be escaped safely and fails with EPERM.
 * Registering from an XML file keeps every quoted path inside the file instead.
 */
function schtasks(args) {
  return run(schtasksExe(), args);
}

/** A .vbs shim so the scheduled run never flashes a console window. */
function writeLauncher() {
  ensureDirs();
  // Each argv entry is wrapped in VBScript-escaped quotes ("" is a literal ").
  const command = relaunchArgv(['update', '--quiet'])
    .map((arg) => (/[\s"]/.test(arg) ? `""${arg}""` : arg))
    .join(' ');
  const vbs = [
    "' Generated by ai-news-wallpaper. Runs the refresh with no visible window.",
    'Set shell = CreateObject("WScript.Shell")',
    `shell.Run "${command}", 0, False`,
    ''
  ].join('\r\n');
  fs.writeFileSync(LAUNCHER_PATH, vbs, 'utf8');
  return LAUNCHER_PATH;
}

function xmlEscape(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function localIso(date) {
  const pad = (n) => String(n).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}` +
    `T${pad(date.getHours())}:${pad(date.getMinutes())}:00`;
}

function currentUser() {
  const domain = process.env.USERDOMAIN || os.hostname();
  const user = process.env.USERNAME || os.userInfo().username;
  return `${domain}\\${user}`;
}

function buildTaskXml(minutes) {
  const start = new Date(Date.now() + 60000);
  const interval = `PT${minutes}M`;
  const user = xmlEscape(currentUser());

  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Author>${user}</Author>
    <Description>Refreshes the desktop wallpaper with the latest AI news headlines.</Description>
  </RegistrationInfo>
  <Triggers>
    <TimeTrigger>
      <Enabled>true</Enabled>
      <StartBoundary>${localIso(start)}</StartBoundary>
      <Repetition>
        <Interval>${interval}</Interval>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
    </TimeTrigger>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>${user}</UserId>
      <Delay>PT1M</Delay>
      <Repetition>
        <Interval>${interval}</Interval>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>${user}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT10M</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>wscript.exe</Command>
      <Arguments>"${xmlEscape(LAUNCHER_PATH)}"</Arguments>
    </Exec>
  </Actions>
</Task>
`;
}

async function installTasks(intervalMinutes) {
  const minutes = Math.min(1439, Math.max(1, Math.round(intervalMinutes)));
  writeLauncher();

  // Task Scheduler wants UTF-16LE with a BOM.
  fs.writeFileSync(TASK_XML_PATH, '\ufeff' + buildTaskXml(minutes), 'utf16le');

  const res = await schtasks(['/Create', '/TN', TASK_NAME, '/XML', TASK_XML_PATH, '/F']);
  if (!res.ok) {
    throw new Error(`Could not create the scheduled task: ${(res.stderr || res.stdout).trim()}`);
  }

  // Clean up tasks created by earlier versions.
  for (const legacy of LEGACY_TASKS) {
    await schtasks(['/Delete', '/TN', legacy, '/F']);
  }

  return { minutes, launcher: LAUNCHER_PATH };
}

async function removeTasks() {
  const results = [];
  for (const name of [TASK_NAME, ...LEGACY_TASKS]) {
    const res = await schtasks(['/Delete', '/TN', name, '/F']);
    results.push({ name, removed: res.ok });
  }
  return results;
}

async function taskStatus() {
  const res = await schtasks(['/Query', '/TN', TASK_NAME, '/FO', 'LIST', '/V']);
  if (!res.ok) return { installed: false };

  const fields = {};
  for (const line of res.stdout.split(/\r?\n/)) {
    const idx = line.indexOf(':');
    if (idx > 0 && !fields[line.slice(0, idx).trim()]) {
      fields[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
    }
  }
  return {
    installed: true,
    state: fields['Status'] || fields['Scheduled Task State'] || 'Unknown',
    nextRun: fields['Next Run Time'] || 'Unknown',
    lastRun: fields['Last Run Time'] || 'Unknown',
    lastResult: fields['Last Result'] || 'Unknown'
  };
}

async function runTaskNow() {
  return schtasks(['/Run', '/TN', TASK_NAME]);
}

module.exports = { installTasks, removeTasks, taskStatus, runTaskNow, TASK_NAME, LAUNCHER_PATH, TASK_XML_PATH };
